<a href="https://colab.research.google.com/github/Jesmeeksingh/Machine_Learning_projects/blob/main/one_hot_encoding_on_cars_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('cars.csv')
df.sample(5)

          brand  km_driven    fuel         owner  selling_price
211      Maruti      20000  Petrol   First Owner         500000
7521  Chevrolet     119000  Diesel  Second Owner         300000
7324       Audi      22000  Diesel   First Owner        2825000
3343   Mahindra     110000  Diesel   Third Owner         245000
875    Mahindra     140000  Diesel  Second Owner         400000

Number of cars in each brand

In [7]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

Total number of unique brands

In [8]:
df['brand'].nunique()

32

Total number of unique fuel cars

In [12]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

Total number of unique fuels

In [10]:
df['fuel'].nunique()

4

Total number of unique car owner types

In [13]:
df['owner'].nunique()

5

Car owner types

In [14]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

#One Hot Encoding using pandas

In [17]:
pd.get_dummies(df,columns=['fuel','owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

#K-1 One Hot Encoding
it is done to remove multicolinearity

In [18]:
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

#One Hot Encoding using SKLearn

In [19]:
from sklearn.model_selection import train_test_split

In [23]:
X_train,X_test,Y_train,Y_test = train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2,random_state=2)

In [25]:
X_train

         brand  km_driven    fuel         owner
5571   Hyundai      35000  Diesel   First Owner
2038      Jeep      60000  Diesel   First Owner
2957   Hyundai      25000  Petrol   First Owner
7618  Mahindra     130000  Diesel  Second Owner
6684   Hyundai     155000  Diesel   First Owner
...        ...        ...     ...           ...
3606      Ford      35000  Diesel   First Owner
5704    Maruti     120000  Petrol   First Owner
6637      Tata      15000  Petrol   First Owner
2575    Maruti      32500  Diesel  Second Owner
7336     Isuzu     121000  Diesel   First Owner

[6502 rows x 4 columns]

In [26]:
X_test

         brand  km_driven    fuel         owner
606    Hyundai      80000  Petrol   First Owner
7575  Mahindra      70000  Diesel  Second Owner
7705    Toyota      68089  Petrol   First Owner
4305   Hyundai      70000  Petrol  Second Owner
2685  Mahindra      97000  Diesel  Second Owner
...        ...        ...     ...           ...
1537    Maruti      50000  Diesel   First Owner
6153    Maruti     111000  Petrol   First Owner
7954    Maruti      40000  Petrol   First Owner
2310   Hyundai      80000  Petrol  Second Owner
712    Hyundai      50000  Diesel   First Owner

[1626 rows x 4 columns]

In [27]:
Y_train

5571    1150000
2038    1689999
2957     580000
7618     150000
6684     320000
         ...
3606     620000
5704     335000
6637     450000
2575     651000
7336    1160000
Name: selling_price, Length: 6502, dtype: int64

In [28]:
Y_test

606      200000
7575     750000
7705    2000000
4305      52000
2685     509999
         ...
1537     650000
6153     220000
7954     320000
2310     150000
712      715000
Name: selling_price, Length: 1626, dtype: int64

In [29]:
from sklearn.preprocessing import OneHotEncoder

In [49]:
OHE = OneHotEncoder(drop = 'first',sparse_output = False,dtype=np.int32)

In [50]:
X_train_new = OHE.fit_transform(X_train[['fuel','owner']])

In [51]:
X_test_new = OHE.fit_transform(X_test[['fuel','owner']])

In [52]:
X_train_new.shape

(6502, 7)

In [53]:
X_test_new.shape

(1626, 7)

In [54]:
import numpy as np

In [55]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new))

array([['Hyundai', 35000, 1, ..., 0, 0, 0],
       ['Jeep', 60000, 1, ..., 0, 0, 0],
       ['Hyundai', 25000, 0, ..., 0, 0, 0],
       ...,
       ['Tata', 15000, 0, ..., 0, 0, 0],
       ['Maruti', 32500, 1, ..., 1, 0, 0],
       ['Isuzu', 121000, 1, ..., 0, 0, 0]], dtype=object)

In [70]:
counts = df['brand'].value_counts()
df['brand'].nunique()
threshold = 100
repl = counts[counts <= threshold].index
pd.get_dummies(df['brand'].replace(repl,'uncommon')).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
654,False,False,False,True,False,False,False,False,False,False,False,False,False
2287,False,False,False,False,False,False,True,False,False,False,False,False,False
6265,False,False,False,False,False,False,False,False,False,False,False,False,True
2158,False,False,False,False,True,False,False,False,False,False,False,False,False
1609,False,False,True,False,False,False,False,False,False,False,False,False,False